local plugin_loader = require('skeleton.plugins')
local plugins = require('skeleton.plugins.list')
local basics = require('skeleton.basics')
local keymaps = require('skeleton.keymaps')
local comments = require('skeleton.comments')
local colors = require('skeleton.colors')

plugin_loader.setup(plugins)
basics.setup()
keymaps.setup()
comments.setup()
colors.setup()